spring:
  sql:
    init:
      mode: never
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${POSTGRES_PWD}
    url: jdbc:postgresql://localhost:5432/oos
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    defer-datasource-initialization: false

app:
  jwt:
    secret: "1234"

logging:
  level:
    telran: debug