spring:
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${POSTGRES_PWD}
    url: jdbc:postgresql://localhost:5432/oos
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    defer-datasource-initialization: true

app:
  jwt:
    secret: ${APP_SECRET}

logging:
  level:
    telran: debug