spring:
  data:
    mongodb:
      uri: mongodb+srv://root:${MONGO_PWD}@cluster0.7rapd.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${POSTGRES_PWD}
    url: jdbc:postgresql://ec2-176-34-211-0.eu-west-1.compute.amazonaws.com:5432/d6qavic7m5rbhp
    username: usajcaezdjijgv
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    defer-datasource-initialization: true

app:
  jwt:
    secret: ${APP_SECRET}

logging:
  level:
    telran: debug