package telran.oos.documents;

import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import telran.oos.api.dto.OrderItemDto;

import java.util.ArrayList;
import java.util.List;

@Data
@NoArgsConstructor
@RequiredArgsConstructor
@AllArgsConstructor
@Document(collection = "baskets")
public class BasketDoc {
    //    @Id                 // making this variable as ID, will be auto-generated by MongoDB
    @NonNull
    private long id;
    @NonNull
    private List<OrderItemDto> basketItems = new ArrayList<>();
    @NonNull
    private long userId;
}
